import test from 'node:test';import assert from 'node:assert/strict';
import {freshState,advance,registerOffline,collect,income,train} from '../dist/core/game.js';import {SaveManager,decode} from '../dist/core/save.js';import {STARTER_PACK} from '../dist/data/offers.js';import {starterEligible,grantStarter,grantReward,rewardContext,MonetizationController} from '../dist/systems/monetization.js';
const now=1800000000000;
function eligible(){const s=freshState(now);Object.assign(s,{level:5,playtime:600,tutorial:3,achievements:['firstMoney','firstJob','firstItem']});s.stats.work=10;s.stats.bought=2;return s;}
const receipt={verified:true,productId:STARTER_PACK.id,transactionId:'tx1'};
test('Starter Pack is gated by experience, time and achievements',()=>{const s=eligible();assert.ok(starterEligible(s));s.playtime=599;assert.ok(!starterEligible(s));s.playtime=600;s.achievements.pop();assert.ok(!starterEligible(s));});
test('verified starter grants specified rewards exactly once',()=>{const s=eligible();assert.equal(grantStarter(s,receipt,now).ok,true);assert.equal(s.gems,90);assert.deepEqual(s.commerce.cosmetics,['mintFrame']);assert.deepEqual(s.commerce.decorations,['starSculpture']);assert.equal(income(s),7.5);assert.equal(grantStarter(s,receipt,now).ok,false);assert.equal(s.gems,90);});
test('missing, wrong product and unverified receipts never grant',()=>{for(const r of [null,{...receipt,verified:false},{...receipt,productId:'other'}]){const s=eligible();assert.equal(grantStarter(s,r,now).ok,false);assert.equal(s.gems,10);}});
test('offline integration applies boost only for actual overlap',()=>{const s=eligible();grantStarter(s,receipt,now);advance(s,now+3600000,true);assert.equal(s.bank,22500);assert.equal(income(s),5);assert.equal(s.boosts.length,0);});
test('simultaneous boosts use maximum, not multiplication',()=>{const s=eligible();grantStarter(s,receipt,now);s.boosts.push({source:'ad',factor:2,startsAt:now,endsAt:now+600000});assert.equal(income(s),10);advance(s,now+1200000,true);assert.equal(s.bank,10500);assert.equal(income(s),7.5);});
test('offline reward survives reload and doubles only this return once',()=>{let s=freshState(now);registerOffline(s,advance(s,now+600000,true));const raw=JSON.stringify(s);s=decode(raw,now+600000);const context=rewardContext(s,'offline');const reward={completed:true,rewardId:'ad1'};assert.equal(grantReward(s,'offline',context,reward,now+600000).ok,true);assert.equal(s.money,6000);assert.equal(s.bank,0);assert.equal(grantReward(s,'offline',context,reward,now+600000).ok,false);});
test('normal collection invalidates outstanding offline ad request',()=>{const s=freshState(now);registerOffline(s,advance(s,now+600000,true));const context=rewardContext(s,'offline');collect(s);assert.equal(grantReward(s,'offline',context,{completed:true,rewardId:'ad1'},now+600000).ok,false);assert.equal(s.money,3000);});
test('cancelled and failed ads never grant; controller always releases busy',async()=>{const s=eligible(),ads={available:true,showRewarded:async()=>({completed:false,rewardId:'no'})},c=new MonetizationController({ads,purchases:{},getState:()=>s,persist(){},clock:()=>now});assert.equal((await c.rewarded('income')).ok,false);assert.equal(s.boosts.length,0);ads.showRewarded=async()=>{throw Error('network')};assert.equal((await c.rewarded('income')).reason,'serviceFailed');assert.equal(c.busy,false);});
test('duplicate clicks during provider wait cause only one request',async()=>{const s=eligible();let finish,count=0;const c=new MonetizationController({ads:{available:true,showRewarded:()=>{count++;return new Promise(r=>finish=r)}},getState:()=>s,persist(){},clock:()=>now});const request=c.rewarded('income');assert.equal((await c.rewarded('income')).reason,'busy');finish({completed:true,rewardId:'unique'});assert.equal((await request).ok,true);assert.equal(count,1);assert.equal(s.daily.incomeAds,1);});
test('daily ad reward requires gift and is limited to once per day',()=>{const s=eligible(),context=rewardContext(s,'daily');assert.equal(grantReward(s,'daily',context,{completed:true,rewardId:'a'},now).ok,false);s.daily.gift=true;assert.equal(grantReward(s,'daily',context,{completed:true,rewardId:'b'},now).ok,true);assert.equal(s.money,150);assert.equal(grantReward(s,'daily',context,{completed:true,rewardId:'c'},now).ok,false);});
test('training reward cannot complete a replacement or already finished course',()=>{const s=eligible();s.money=1000;train(s,'technology',now);const context=rewardContext(s,'training');assert.equal(grantReward(s,'training',context,{completed:true,rewardId:'t1'},now).ok,true);assert.equal(s.skills.technology,1);train(s,'creativity',now+1000);assert.equal(grantReward(s,'training',context,{completed:true,rewardId:'t2'},now+1000).ok,false);assert.equal(s.skills.creativity,0);});
test('v2 migration retains all gameplay while adding safe commerce defaults',()=>{const old=eligible();old.saveVersion=2;old.money=456;delete old.commerce;delete old.boosts;const s=decode(old,now);assert.equal(s.money,456);assert.equal(s.level,5);assert.equal(s.commerce.starterOwned,false);assert.deepEqual(s.boosts,[]);assert.equal(s.saveVersion,4);});
test('v3 keeps boost interval, reward receipts and ownership across save/load',()=>{const map=new Map(),store={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},m=new SaveManager(store),s=eligible();grantStarter(s,receipt,now);m.save(s);const r=m.load(now+900000);assert.equal(r.bank,6750);assert.equal(r.commerce.starterOwned,true);assert.equal(r.boosts[0].endsAt,now+1800000);assert.equal(grantStarter(r,receipt,now+900000).ok,false);});
